### ISSUE TITLE
Steady state simulation

### ISSUE THREAD

**Issue by jdasmith** [UKFELs/Puffin#41]
... something similar to the ability in Genesis to swtich on a flag for ITDP (basically run 'steady state' through as much undulator as it takes to saturate).

Maybe this is a capability we should look up.

**Comment by mightylorenzo** [comment]
OK  - this is kindof implemented and working now. Not strictly steady-state, but using periodic boundary conditions, so assuming an infinitely long beam. We can still model sub-period phenomena. 

The 3D sims using this are very fast compared to a 'full' temporal run. It is not 'official' yet, and certainly, the interface needs drastically cleaned up, but if desired, you can get it in the dev-period branch.

It is not integrated with the rest of Puffin, so you'll need to compile both versions separately. The same input files are used for both, which causes minor niggles in the periodic version. The biggest one is that you need to set up the simulation domain with exactly to correct length (probably should be an integer number or radiation wavelengths), and you have to ensure periodic initial conditions, and you need to put in this length for both the beam and the field mesh. This will be cleared up over the next few weeks for more convenient use.

Initial results are promising - CPU time for CLARA runs go from ~1000 core hours to 2 core hours. Much better for scans and optimization.

**Comment by mightylorenzo** [comment]
All integrated - can now be switched on with the periodic mesh type option in the main input file.
