### ISSUE TITLE
Cmake and Bilder Issue

### ISSUE THREAD

**Issue by piotrt75** [UKFELs/Puffin#51]
Recently the Bilder updated Cmake to ver 3.7.x which causes me a lot of trouble - I just can't pass through cmake. The message I see in cmake is stating that it can't find fftw3 libs although the paths are defined properly - this is not happening in cmake 3.4.x (bilder downloaded on 2nd December 2016). Same machine+system (Ubuntu mate 16.04) used.

[cmake_script.txt](https://github.com/UKFELs/Puffin/files/711200/cmake_script.txt)

[cmake_run.txt](https://github.com/UKFELs/Puffin/files/711208/cmake_run.txt)

**Comment by mightylorenzo** [comment]
As far as I could tell, some flags were not explicitly set in SciMake, which was causing issues in the latest versions of CMake. They may have changed some default or assumed behaviour. In particular, the flag TFP_ALLOW_LIBRARY_DUPLICATES in SciFindPackage.cmake was causing trouble. I've manually put in an explicit flag in its place, which is absolutely not the best solution for SciMake, but it works for all cases tested in Puffin. Resolved in commit 0cf7789
