### ISSUE TITLE
MPI compilers not found

### ISSUE THREAD

**Issue by jhein32** [UKFELs/Puffin#62]
Hi,

I am building on Centos 7 with gcc 6.4.0 and OpenMPI 2.1.2 and CMake 3.9.5

I used a source tarball from https://github.com/UKFELs/Puffin/archive/v1.9.0-alpha.tar.gz

I had a few issues:

First it wouldn't configure for MPI, until I added -DENABLE_PARALLEL=1 to the cmake command.  As far as I can tell this is not documented in the BUILD.md file.

While is seems to react to the compiler environment variables CC, CXX, ... it doesn't react to the variables MPICC, MPICXX and keep trying to resolve the mpi library from gcc.  Once I added 

`-DMPI_C_COMPILER=$MPICC -DMPI_CXX_COMPILER=$MPICXX -DMPI_FORTRAN_COMPILER=$MPIFC`

to the cmake command, it configured correctly.  You might want to update your BUILD.md for these issues.

I hope this is appreciated.

**Comment by mightylorenzo** [comment]
My response is quite late - but this is very much appreciated! Build instructions updated in commits 6c4e25c, 64e3d6b, bcb0d09, and f9a620c.
